# .goreleaser.yml
# Build customization
builds:
  - binary: chicks

    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
