# .goreleaser.yml
# Build customization
builds:
  - binary: chicks
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm

universal_binaries:
  - replace: true
